sudo: required
dist: trusty
language: php

php :
  - 7.1

branches:
  only:
    - master 
    - develop
#jalanqan install pacage dll
# Precompile
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate


# Main Execution (Build)
script:
  - ./vendor/bin/phpunit


# when the condision main execution finish
after_success: